// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOaVEQuHAyDYUu_96MeA_JGx6psdCCe7U',
    appId: '1:361117106259:web:2f4a5ee790497911dcc6a6',
    messagingSenderId: '361117106259',
    projectId: 'emamadmin',
    authDomain: 'emamadmin.firebaseapp.com',
    storageBucket: 'emamadmin.firebasestorage.app',
    measurementId: 'G-X04TQY2ZWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwbNiFmiy2LusyuaoRKibf5b2exM84Pfs',
    appId: '1:361117106259:android:e3fa9d7b2f5eba3adcc6a6',
    messagingSenderId: '361117106259',
    projectId: 'emamadmin',
    storageBucket: 'emamadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKn_IOtQCNmnCbeVx0b1fp-gF7EAw2Do',
    appId: '1:361117106259:ios:978a18ba5e2bc7b4dcc6a6',
    messagingSenderId: '361117106259',
    projectId: 'emamadmin',
    storageBucket: 'emamadmin.firebasestorage.app',
    iosBundleId: 'com.example.emamAdminWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKn_IOtQCNmnCbeVx0b1fp-gF7EAw2Do',
    appId: '1:361117106259:ios:978a18ba5e2bc7b4dcc6a6',
    messagingSenderId: '361117106259',
    projectId: 'emamadmin',
    storageBucket: 'emamadmin.firebasestorage.app',
    iosBundleId: 'com.example.emamAdminWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOaVEQuHAyDYUu_96MeA_JGx6psdCCe7U',
    appId: '1:361117106259:web:6782559618a70979dcc6a6',
    messagingSenderId: '361117106259',
    projectId: 'emamadmin',
    authDomain: 'emamadmin.firebaseapp.com',
    storageBucket: 'emamadmin.firebasestorage.app',
    measurementId: 'G-YM7CN36B0X',
  );
}
